resolver: lts-13.20
packages:
- '.'

extra-deps:
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 31e1466e35cee9a91fa6678d73c938f0f44759eb

allow-newer: True

ghc-options:
    "$locals": -Werror
