resolver: lts-15.11
packages:
- '.'

extra-deps:
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 8cb68def2563e2ebcbdcbec688b326b9f3fa1dd7

allow-newer: True

ghc-options:
    "$locals": -Werror
