resolver: lts-11.8
packages:
- '.'
extra-deps:
- haskell-src-exts-1.20.2
- git: https://github.com/robertjlooby/descriptive
  commit: 9419a51e272d6f6738cd3e81c652790e8b4bd11b
- path-0.5.9
- path-io-1.2.0

allow-newer: True
