resolver: lts-20.4
packages:
- '.'

extra-deps:
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: d1a86659a8c5d9526b9b23b6ba9538f5aed2e4a7

allow-newer: True

ghc-options:
    "$locals": -Werror
