resolver: lts-23.0
packages:
- '.'

extra-deps:
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 443776e416f3fc3c2b56cbd5b11beaf022365c9d

allow-newer: True

ghc-options:
    "$locals": -Werror
