resolver: lts-19.18
packages:
- '.'

extra-deps:
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: a2225286fa8349de93b4c0ccc85b8cae8c5d8d05

allow-newer: True

ghc-options:
    "$locals": -Werror
